name: box2d
version: 0.4.0
authors:
- Kevin Moore <kevmoo@google.com>
- Srdjan Mitrovic <srdjan@google.com>
- Filip Hracek <filiph@google.com>
description: A Dart 2D physics engine
homepage: https://github.com/google/box2d.dart
environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"
dependencies:
  vector_math: '>=2.0.0 <3.0.0'